### ISSUE TITLE
Can you add this to Grade an Maven?

### ISSUE THREAD

**Issue by xRealNeon** [ByteDream/untis4j#1]
And your library doesn't work because when I use one of the examples I get an exaction that the URL protocol is not present and when I add https:// I get an exception null

**Comment by ByteDream** [comment]
Yes I can add gradle and maven support in the next update. I'm currently writing a discord bot based on this library an I never got an error (i've tested it with multiple accounts). Do you get this error while using the `login` method? If yes, you mabye using the wrong server url. When you are at the webuntis login screen the url is `https://xyz.webuntis.com/WebUntis/?school=abc-school#/basic/main` (for example). For the url parameter in the `login` method you have to extract the https and the server (or base url), in this case it is `https://xyz.webuntis.com`. For the school name you have to enter the text between `...?school=` and `#/basic...` in this case `abc-school`. The final result for this example would be `Session.login("username", "password", "https://xyz.webuntis.com", "abc-school")`. If you've already tried this and still get the error you can comment the error here so I can analyze it

**Comment by xRealNeon** [comment]
If I catch all exceptions and print them out I only get null

**Comment by ByteDream** [comment]
What happens if you remove the try catch and run it again?

**Comment by xRealNeon** [comment]
Instant crash

**Comment by ByteDream** [comment]
And error message / stack trace?

**Comment by xRealNeon** [comment]
Nothing

**Comment by ByteDream** [comment]
Which example do you use?

**Comment by xRealNeon** [comment]
The first one without any action just the login

**Comment by ByteDream** [comment]
The login itself doesnt give any response. Try to print out `session.getKlassen()`

**Comment by xRealNeon** [comment]
Im not on my pc right now ill do it and report back what it does

**Comment by ByteDream** [comment]
Ok^^

**Comment by xRealNeon** [comment]
like i said when i do https:// and then the server url it crashes without any output

**Comment by ByteDream** [comment]
Even if you try `session.getKlassen()`?

**Comment by xRealNeon** [comment]
yes

**Comment by ByteDream** [comment]
Do you use the release 1.0 jar?

**Comment by xRealNeon** [comment]
the latest from the readme

**Comment by ByteDream** [comment]
Hm ok. I could send the pre 1.1 release jar here. Maybe it will work then but currently im not on my pc, so you have to wait about 2.5 hours. Alternatively you can download the [source code](https://github.com/ByteDream/untis4j/archive/master.zip), unzip it and try include it into your project if not want to wait for my jar

**Comment by ByteDream** [comment]
Here's the jar file (its zipped because github don't support jar file uploads in issues): [untis4j-pre-1.1.zip](https://github.com/ByteDream/untis4j/files/5262589/untis4j-pre-1.1.zip)

**Comment by xRealNeon** [comment]
doesn't work

**Comment by ByteDream** [comment]
hmm. Could you paste your code here?

**Comment by xRealNeon** [comment]
```
 try {
            Session session = Session.login("", "", "https://borys.webuntis.com", "");  // create a new webuntis session

            System.out.println(session.getKlassen());

            session.logout();  //logout
        } catch (LoginException e) {  // this exception get thrown if something went wrong with Session.login
            System.out.println("Failed to login: " + e.getMessage());
            return;
        } catch (IOException e) {  // if an error appears this get thrown
            e.printStackTrace();
            return;
        }
```

**Comment by ByteDream** [comment]
Well i copy pasted the code (and used my username, password, server and school name) and it works fine. Weird

**Comment by xRealNeon** [comment]
yeah

**Comment by xRealNeon** [comment]
Oh, I didn't mention I'm using this in an app

**Comment by ByteDream** [comment]
Then it will probably be an android app. Does the android version you've chosen java8?

**Comment by xRealNeon** [comment]
I use the SDK version 26

**Comment by ByteDream** [comment]
Currently I have tested the api only with the "normal" Java. Android support is not bad at all, so I will test the api on android as well. If there is any progress / if i find the bug or whatever this is, i'll post it here^^

**Comment by ByteDream** [comment]
I've used a empty activity and added: the api and the org.json library; `android.permission.INTERNET` to the android manifest file.
Then I added the following to the `onCreate(...)` method: 
```java
this.requestPermissions(new String[]{Manifest.permission.INTERNET}, 0);
Thread t = new Thread(() -> { //if i would do this without a thread a 'android.os.NetworkOnMainThreadException' gets thrown
        try {
             Thread.sleep(5000);
        } catch (InterruptedException e) 
              e.printStackTrace();
        }
        try {
              Session session = Session.login("username", "password", "https://xyz.webuntis.com", "a-school");

              System.out.println(session.getKlassen());
        } catch (IOException e) {
              e.printStackTrace();
        }
});
t.start();
```
And it worked
![image](https://user-images.githubusercontent.com/63594396/93926784-7e131680-fd07-11ea-940a-11b543960130.jpg)

Here is the app if you want to test it: [MyApplication.zip](https://github.com/ByteDream/untis4j/files/5263480/MyApplication.zip)

**Comment by ByteDream** [comment]
Does it work now? I'll close this issue with the next version if you wont't answer

**Comment by xRealNeon** [comment]
I get this error when i use session.getKlassen() and without it it works kind of
`    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)
`

**Comment by xRealNeon** [comment]
the only thing that works is session.getInfos()

**Comment by ByteDream** [comment]
Have you tried to run the zipped app that i've sent?

**Comment by ByteDream** [comment]
There is no Maven / Gradle support planned as I am not a big fan of it. And since I haven't received an answer for a long time, I think the Android problem is solved (or you use a different API).
