### ISSUE TITLE
Issue while calling getTeachers.

### ISSUE THREAD

**Issue by DxsSucuk** [ByteDream/untis4j#6]
I wanted to inform you that the getTeachers methode doesnt give you any data about the Teachers. I checked if i have the API-Permissions to do that and as i checked with the JS API it worked! I got the Data of the Teachers. But in the timetable there isn't any data saved for the Teachers.

**Comment by ByteDream** [comment]
When I do
```java
Timetable timetable = session.getTimetableFromClassId(LocalDate.now(), LocalDate.now(), <class id>);
System.out.println(timetable.getTeachers());
```
the teachers are shown normally

**Comment by DxsSucuk** [comment]
Well thats weird.

**Comment by ByteDream** [comment]
Closing due issue inactivity
