### ISSUE TITLE
Build Tools / Gradle

### ISSUE THREAD

**Issue by warriorzz** [ByteDream/untis4j#8]
Hey, I would like to use your library, but there is an issue - or more likely, a quality of life feature. Currently, I am using [gradle](https://gradle.org/) for building my applications and I would like to add your library as a dependency in gradle. As you aren't publishing it to any maven repository, I can't include it as usual. Luckily, gradle supports [adding a git repository as a dependency](https://stackoverflow.com/a/56787382), but you haven't comitted any build files in your repository. Is there any way to add them to the repository, so I can use it as a dependency?

**Comment by ByteDream** [comment]
Since i'm relatively busy at the moment and haven't used any java build system yet, it would be nice if someone could make a PR which adds the needed files for a build system integration

**Comment by ByteDream** [comment]
Support was added in #9 by @warriorzz, thanks!
